# 数据库配置
db:
  mysql:
    host: 43.139.229.15 
    username: 'root'
    password: '123456'
    database: 'testdb'
    port: 3306
    synchronize: true

# jwt
jwt:
  secretkey: 'you_secretkey'
  expiresIn: '1d'

# 权限 白名单配置
perm:
  router:
    whiteList: [
      { path: '/register', method: 'POST'},
      { path: '/login', method: 'POST'},
    ]